### PR TITLE
New features

### PR DESCRIPTION
**Pull request by Ghitu**
Hello, 

I've added a few new features that I needed for one of my projects. If you wish, you can merge them into your repository.

The features are:
- **The ability to register users (http://xmpp.org/extensions/xep-0133.html#add-user)**

Example code

```
 use Fabiang\Xmpp\Protocol\Register;
 ...

 $options = new Options($chatUrl.':5222');
 $client = new Client($options);
 $options->setUsername($adminUsername)->setPassword($adminPassword);

 $user = new Register;
 $user->setTo($chatUrl)
      ->setFrom($adminUsername.'@'.$chatUrl)
      ->setJabberID($userUsername.'@'.$chatUrl)
      ->setPassword($userPassword);

  $client->send($user);
  $sid = $options->getSid();
  $user->setSID($sid)->setStep('two');
  $client->send($user);
```
- **vCard support**
  _At the moment can set only: First Name, Last Name, URL (to user profile), Image_

Example code

```
 use Fabiang\Xmpp\Protocol\vCard;
 ...

 $options = new Options($chatUrl.':5222');
 $client = new Client($options);
 $options->setUsername($userUsername)->setPassword($userPassword);

 $vcard = new vCard;
 $vcard->setFirstname($userFirstName)
            ->setLastname($u->last_name)
            ->setJabberID(strtolower($u->username).'@'.Config::get("app.chat_url"))
            ->setUrl($u->getUserUrl());

 $mime = 'image/jpeg'; // image mime type
 $image = file_get_contents($image_url);
 $vcard->setMime($mime)->setImage(base64_encode($image));

$client->send($vcard);
$client->disconnect();
```
- **Block User (https://xmpp.org/extensions/xep-0191.html#block)**

Example code

```
 use Fabiang\Xmpp\Protocol\BlockUser;
 ...

$options = new Options($chatUrl.':5222');
$client = new Client($options);

$options->setUsername($userUsername)->setPassword$userPassword);

$blockUser = new BlockUser;
$blockUser->setFrom($userUsername.'@'.$chatUrl)
         ->setJabberID($blockUserUsername.'@'.$chatUrl);
$client->send($blockUser);

$client->disconnect();
```
- **Unblock User (https://xmpp.org/extensions/xep-0191.html#unblock)**

```
 use Fabiang\Xmpp\Protocol\UnblockUser;
 ...

$options = new Options($chatUrl.':5222');
$client = new Client($options);

$options->setUsername($userUsername)->setPassword$userPassword);

$unBlockUser = new UnblockUser;
$unBlockUser ->setJabberID($blockedUserUsername.'@'.$chatUrl);
$client->send($unBlockUser);

$client->disconnect();
```

Hope this helps
Alin

### CODE REVIEW

**Comment by varakh** [comment]
:+1: I need those features too. @fabiang can you look into this?

**Comment by Ghitu** [comment]
@varakh I am not planning to add other features for the moment. I can help you with the get if you give me more details.

**Comment by varakh** [comment]
@Ghitu Nevermind. As long as this does not get merged I won't need those features either. I will come back to this if it got merged. Thanks anyway.

**Comment by fabiang** [comment]
Cherry picked your relevant commit and merged locally. Thanks for the work!

**Comment by Ghitu** [comment]
@fabiang Thank you!

**Pull request closed without merging**
