### PR TITLE
New features: register user, change password, create room, config room, add member to a room, bookmarks, vCard, avatar

### PR DESCRIPTION
**Pull request by eLFuvo**
This version will conflict with 0.7.0 version.

### CODE REVIEW

**Comment by fabiang** [comment]
Since Version 0.7 we have vCard support and support for registering an user.

I would recommend you split this PR into separate PRs for every new feature. Otherwise I'm not willing to merge this an resolve the conflicts.

**Comment by eLFuvo** [comment]
Just compare realization of this features:
vCard:
https://github.com/eLFuvo/xmpp/blob/master/src/Protocol/User/VCardUpdate.php
example: https://github.com/eLFuvo/xmpp/blob/master/examples/vcard.php

Reqister user:
https://github.com/eLFuvo/xmpp/blob/master/src/Protocol/User/RegisterUser.php
example: https://github.com/eLFuvo/xmpp/blob/master/examples/register.php

Its follows PSR4 code style and realize XMPP protocol better than current code.
Current features for vCard and registering user must be overwiriten/apended by this request.

**Comment by fabiang** [comment]
Regardless which implementation is the better one, please make a PR depending on the current master and current implementation.

**Comment by rheman** [comment]
Hi eLFuvo.
I am using your custom fabiang library but StanzasErrorException is not triggered .
 am using the library for managing my ejabberd user. But https://xmpp.org/extensions/xep-0086.html seems to be deprecated and was rolled into the new [xmpp-core] http://xmpp.org/rfcs/rfc6120.html. Stanza errors are defined in https://xmpp.org/rfcs/rfc6120.html#stanzas-error and https://xmpp.org/rfcs/rfc3920.html#rfc.section.9.3.3.
So when try to register a user throuh fabiang library everything works perferctly. But when I try to register one more time and existing user the StanzasErrorException is not triggered.
Could someone help me ?
I dont know what's wrong with my settings.
Best ragard.

**Pull request closed without merging**
